### ISSUE TITLE
AccountPayout attributes 

### ISSUE THREAD

**Issue by karteekkommana** [danibram/trustly-client#10]
AccountPayout attributes contain other object "SenderInformation" to which attribute properties need to add.
<img width="589" alt="screen shot 2017-12-19 at 11 11 36" src="https://user-images.githubusercontent.com/6124983/34152018-6b3d951e-e4ad-11e7-8f18-de30609c5cee.png">

**Comment by danibram** [comment]
Its already added on the definition `attributesFields: ['SenderInformation'],`
