### ISSUE TITLE
Api for trustly Live endpoint

### ISSUE THREAD

**Issue by karteekkommana** [danibram/trustly-client#13]
hi Daniel 
This repo works great for Turstly test api endpoint. 

Will it be possible to have trustly production endpoint https://api.trustly.com/1 in this repo?

**Comment by danibram** [comment]
As is written in the README you only have to change the environment variable:

```
[optional] 'environment': By default is "development", and it does the http calls to trustly development environment (https://test.trustly.com/api/1), if you pass production it turns to https://trustly.com/api/1, so remember to change that variable when you go to production
```
